### PR TITLE
Use pull_request to run github actions instead of push

### PR DESCRIPTION
**Pull request by harriswong**
## Description
Use `pull_request` instead of `push` to trigger event. This change should allow:
pull_request: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
push: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

1. GitHub Action to run on PR that's made from forked repo
2. GitHub Action should run every time a new commit is pushed to the PR.

### Related issue(s)
Closes https://github.com/Automattic/woocommerce-services/issues/2395

### Steps to reproduce & screenshots/GIFs
Make sure pipeline runs.

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Comment by harriswong** [comment]
Initial check runs. I am going to make a new commit to see if the pipeline runs again.

**Comment by harriswong** [comment]
Confirmed check runs on new commits made to the same PR. Removing test commit, rebasing develop.

**Review by frosso — APPROVED** [review]
Seems to be working well 👍 

To test it, I created a forked repo on my profile, then created a PR against this repo.
To confirm that it worked, I first only updated the `js_tests` configuration and verified that the `php_tests` did not report well.

Overall seems like a safe change 👍

**Comment by harriswong** [comment]
@frosso Thanks for the check by actually forking the repo!

**Pull request merged**
