### PR TITLE
Remove validation from PackageDialog

### LINKED ISSUE #1745: Package options can't be saved with no payment options
If you try to add a package with no payment options added, you run into an error message:
image

### PR DESCRIPTION
**Pull request by bor0**
Fixes #1745.

### CODE REVIEW

**Comment by bor0** [comment]
@c-shultz I assigned you for a review since @budzanowski is AFK.

Unrelated to these changes but with a similar scenario, can you please confirm that you can go through the process without having any cards entered?

I am not sure if it's my environment but here's what I get:

Untitled

**Comment by c-shultz** [comment]
I have seen the 500 error really intermittently (but not while testing this PR). I've always attributed it to something not working quite right with my environment. Restarting things seemed to resolve it. The environment is so complex, it's hard to tell the root cause. :\

We should keep an eye for it though in case there's a real issue...

**Comment by bor0** [comment]
@c-shultz do you think we should re-introduce the logic for `To purchase shipping labels...`?

**Comment by c-shultz** [comment]
@bor0, I don't think we want that anymore since one of the big changes in this release is to not require the credit card until after all the label options are selected.

**Comment by bor0** [comment]
@c-shultz ahh I see, I remember now. Thanks!

**Comment by bor0** [comment]
@c-shultz got more info from @DanReyLop on the errors we're seeing. It seems they are related to our dev envs only.

Reference: https://a8c.slack.com/archives/CKNC7KACA/p1572390559102600

**Pull request merged**
