### PR TITLE
Replace TokenField with FormTokenField

### PR DESCRIPTION
**Pull request by harriswong**
## Description
Replace Calypso's `TokenField` with WP's component `FormTokenField`.

### Related issue(s)
Relates to https://github.com/Automattic/woocommerce-services/issues/2333

### Steps to reproduce & screenshots/GIFs
1. Go to WooCommerce -> Settings -> Shipping Zones -> USPS Live Rates
2. Check that the "Shipping Classes" drop down still works.

Before with Calypso:
image

After, with WP's component: 
image

### Checklist

- [x] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Review by waclawjacek — COMMENTED** [review]
This is how it looks on my machine. Any idea why this is the case?

Screen Capture on 2022-11-28 at 20-03-05

**Comment by harriswong** [comment]
🤔  Did you wait for the whole `npm i` to finish running?

**Comment by waclawjacek** [comment]
Yep!

**Comment by waclawjacek** [comment]
Could you please give this another look?

**Comment by harriswong** [comment]
Hey @waclawjacek , I just pulled and fixed the conflict. I still don't see what you were seeing:
image

**Comment by harriswong** [comment]
I was wondering if it's the longer class name you have, but I still don't see the same issue:
image

**Review by waclawjacek — CHANGES_REQUESTED** [review]
@harriswong Could you please update your WP, WC, WCS&T versions to the most recent ones and check what you see then? I am still getting the same thing.

**Comment by harriswong** [comment]
I can reproduce this. I will have to dig a little bit into it.

**Comment by harriswong** [comment]
Fixed and now it looks like:
image

Updated the styles by using the FormTokenField from storybook https://wordpress.github.io/gutenberg/?path=/docs/components-formtokenfield--default. I think there are some opportunities here for us to clean up the whole calypso styles embedded here https://github.com/Automattic/woocommerce-services/blob/trunk/assets/stylesheets/style.scss. But that could be done after Calypso is removed. 

image

**Review by waclawjacek — CHANGES_REQUESTED** [review]
Aha, great job! Looks and works well. But I feel I have to request changes because I think we should sort out the border situation; otherwise, the field will look out of place alongside other fields.

## Current look

Markup on 2023-05-03 at 14:11:57

## Previous look

image

**Comment by harriswong** [comment]
- Matched border colour
- Removed border
Please take a look again. @waclawjacek

**Comment by harriswong** [comment]
No longer removing Calysp from WCS&T (https://github.com/Automattic/woocommerce-services/issues/2333). Putting this on hold.

**Review by waclawjacek — APPROVED** [review]
Reviewing anyway so this doesn't get stale! :) LGTM! :shipit: Thank you for the updates.

**Comment by harriswong** [comment]
Closing. No longer needed.

**Pull request closed without merging**
