### PR TITLE
Disable E2E tests unless env(DONT_SKIP_E2E_TESTS) is present

### LINKED ISSUE #2305: Temporarily disable E2E tests blocks pipeline due to errors
Summary
The E2E tests are failing and are blocking our pipelines. These tests are not being helpful at the moment until we fix them. Temporarily disable them in `.travis.yml` until the tests are fixed, or until we moved over to the [new E2E setup](https://github.com/Automattic/woocommerce-services/issues/2055).

### PR DESCRIPTION
**Pull request by waclawjacek**
## Description

E2E tests are currently failing. This PR adds support for the `DONT_SKIP_E2E_TESTS` environment variable that, unless present, disables the `E2E tests` Travis job by default.

Once E2E tests are fixed, the condition can be removed from `.travis.yml`.

### Related issue(s)

Fixes #2305.

### Steps to reproduce & screenshots/GIFs

**Before:** E2E tests fail on all PRs. Example: #2303.

**After:** E2E tests are not executed unless the `env(DONT_SKIP_E2E_TESTS)` variable is present either in `.travis.yml` or the repository settings. See the [Environment Variables chapter of the Travis documentation](https://docs.travis-ci.com/user/environment-variables/) for more information.

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Review by superdav42 — APPROVED** [review]
Works for me

**Comment by superdav42** [comment]
I tried triggering the travis build with a custom config to set the env var to force the e2e to run but the test is still pending. Not sure what's wrong but I assume it's a problem with travis. https://travis-ci.org/github/Automattic/woocommerce-services/builds/756141514/config

**Comment by c-shultz** [comment]
Oh interesting, @superdav42! That's where the `api` config is coming from?
image

How did you trigger that?

**Comment by waclawjacek** [comment]
Oh, I was wondering about that! Yeah, looks like it might be an issue with Travis. Thanks so much for posting about it! I'm also curious about Chris's questions.

**Comment by superdav42** [comment]
I choose Trigger Build in the Other Options drop down and choose the branch then entered the yml config I wanted.
Screenshot from 2021-01-26 12-39-07
Of course it didn't exactly work yet and I was just looking for a way to trigger a build and I found it. In future it may be useful to test new configs without having to change code.

**Comment by waclawjacek** [comment]
@superdav42 This is really cool!

I did some experimentation with this feature and I could not get this to run correctly on the repository, including when I didn't pass any custom config like you did in the screenshot.

I created a test private repo, replicated the Travis settings from the `woocommerce-services` repo, and placed the following config inside, and it worked when attempting a custom build:

```yaml
language: php
os: linux

jobs:
  include:
  - php: 7.3
    script: echo "The first job ran! 🦀"
  - php: 7.3
    if: env(DONT_SKIP_E2E_TESTS) IS present
    script: echo "The second job ran! 🐢"
```

Here are the results for both when using a custom config and when using no custom config at all:

## With custom config (`DONT_SKIP_E2E_TESTS=1` is present)

### Config

Test build with custom config - "View config" page

The `api` section is present, displaying the custom config.

### Job log

Test build with custom config - "Job log" page

Two jobs were executed, both successful.

## Without custom config

### Config

Test build without custom config - "View config" page

No `api` section is present, indicating that there was no custom config provided.

### Job log

Test build without custom config - "Job log" page

The job log is displayed because there was only one job.

---

We already know that with the current PR code, the build is executed and succeeds without running the E2E tests ([the Travis build is here](https://travis-ci.org/github/Automattic/woocommerce-services/builds/755672851)):

Successful build of the current state of this PR

Based on this, I will push a commit with the env variable `DONT_SKIP_E2E_TESTS=1` to this PR to see if this will trigger a build that is actually executed. If it does, I will revert the change in the Travis config file and post the link to the (hopefully failing, indicating that the config does work) build for future reference.

**Comment by waclawjacek** [comment]
It turns out the build errors were caused by travis-ci.org not processing the build jobs. The tests that I ran on my private repository (which succeeded) were ran on travis-ci.com.

Once the builds are processed correctly again, the things to test before merging are:

1. Trigger a custom build with the following custom config:

```yaml
env:
  - DONT_SKIP_E2E_TESTS=1
```

This build should include E2E tests and it is expected to fail.

2. Trigger a custom build without a custom config. This build should **not** include E2E tests and should succeed.

**Comment by c-shultz** [comment]
I'm going to try re-triggering a build by closing a reopening the PR

**Comment by c-shultz** [comment]
All good on travis-ci.com. I'll go ahead and merge.

**Pull request merged**
