### PR TITLE
chore: rename WCS to WC Shipping & Tax

### PR DESCRIPTION
**Pull request by frosso**
## Description
Renaming of user-facing `WooCommerce Service(s)` strings to `WooCommerce Shipping & Tax(es)`.

## Related Issue
Helps with https://github.com/Automattic/woocommerce-shipping-issues/issues/104

### CODE REVIEW

**Comment by c-shultz** [comment]
@frosso, we'll go ahead and release this with all the other pending changes on the 13th. Is it ready for review now?

**Comment by frosso** [comment]
@c-shultz I updated the description(s) based on the newer marketing documents.
I am still waiting for the updated assets for the .org entry.

Would you like me to open this for review, even though I'm still waiting on the new assets?
I can open a PR for the updated assets separately.

**Comment by c-shultz** [comment]
@frosso, I would go ahead with opening it up for review. The .org assets can be separate if needed.

**Review by c-shultz — COMMENTED** [review]
@frosso ,

Why did you go with "Shipping and Tax**es**" in some cases instead of just "Shipping and Tax"
My assumption is that it would just be "Tax" in all cases, but maybe I missed a conversation about this.

**Review by c-shultz — CHANGES_REQUESTED** [review]
Everything looks good and tests well! My only comment is that I think we should just be consistent and use "Tax" instead of "Taxes"

**Comment by frosso** [comment]
Chatted with @c-shultz offline.
The "Taxes" (instead of "Tax") came from the adjusted marketing material.

Confirmed to keep "Tax" for consistency, will change later if needed.

**Review by c-shultz — APPROVED** [review]
The changes look good!

I ran through:
- Settings
- Status screen
- Label purchase
- Live rates

Everything is working well and the string update is reflected correctly everywhere. 🚢

**Comment by c-shultz** [comment]
>changelog entry    
I'm glad you at least remembered to check for that 💯

**Pull request merged**
