### PR TITLE
Update e2e ping

### LINKED ISSUE #2590: E2E tests failed to run
### Description

It looks like the `Run npm run test:e2e-docker-up` ran fine and the containers are up in the log. But the ping check failed. Blocking pipeline to merge.

https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:56
```
Run npm run test:e2e-docker-ping

> woocommerce-services@1.26.3 test:e2e-docker-ping /home/runner/work/woocommerce-services/woocommerce-services
> bash ./tests/bin/wait-for-e2e-build.sh

Testing URL: http://localhost:8084

Thu Nov  3 18:23:2[7](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:8) UTC 2022 - Docker container is still being built
Thu Nov  3 1[8](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:9):23:38 UTC 2022 - Docker container is still being built
Thu Nov  3 18:23:48 UTC 2022 - Docker container is still being built
Thu Nov  3 18:23:58 UTC 2022 - Docker container is still being built
Thu Nov  3 18:24:08 UTC 2022 - Docker container is still being built
Thu Nov  3 [18](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:19):24:18 UTC 2022 - Docker container is still being built
```

### PR DESCRIPTION
**Pull request by bartech**
### Related issue(s)
Closes #2590 

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Comment by harriswong** [comment]
Curious how did you figure this out?

**Review by harriswong — APPROVED** [review]
🚢 PIpeline passed, LGTM.

**Comment by harriswong** [comment]
Merging for you.

**Comment by dustinparker** [comment]
> Curious how did you figure this out?

We ran the e2e tests locally and realized the "Ready" page was not being created. That page is created in the Docker entrypoint.sh file for the `woocommerce_services_wordpress-cli` container [here](https://github.com/woocommerce/woocommerce/blob/17fe37cafe40df624fc0200699744fdbf2bb4b59/packages/js/e2e-environment/docker/wp-cli/entrypoint.sh#L58-L63). The build context for that container is set [here](https://github.com/woocommerce/woocommerce/blob/17fe37cafe40df624fc0200699744fdbf2bb4b59/packages/js/e2e-environment/docker-compose.yaml#L51-L52).

So we ran `docker exec -it woocommerce_services_wordpress-cli entrypoint.sh` a few times and noticed it would exit while waiting for Jetpack to install but without any indication as to why. We then manually installed Jetpack on localhost:8084 and ran the entrypoint.sh again. When the script went to activate Jetpack, it output a message that Jetpack required at least WP 6.0 and couldn't be activated.

**Pull request merged**
