### PR TITLE
Add button to create custom package on shipping label page. 

### LINKED ISSUE #1647: Introduce custom package setting into the create label flow
Currently the ability to create custom packages is only available buried deep in the settings. We want to add this to the create label flow.

Work with @olaolusoga on how to incorporate this into the accordion

### PR DESCRIPTION
**Pull request by superdav42**
Fixes #1647.

### CODE REVIEW

**Comment by roykho** [comment]
I am seeing no packages listed for the dropdown.

**Comment by roykho** [comment]
Probably not apart of this PR but maybe it would be good to pre-select the custom package that was just added? Currently after you created a custom package, it still asks you to pick a package from dropdown.

**Comment by roykho** [comment]
Currently the "Add Package" button is butted up against the "Select a package" dropdown. I would suggest we push the button down a little so it has some breathing room.

**Comment by bor0** [comment]
@roykho one more round, please.

**Comment by laurendavissmith** [comment]
@bor0 it doesnt look like this is following the figma design

Screen Shot 2019-09-19 at 12 37 06 PM

**Comment by laurendavissmith** [comment]
Screen Shot 2019-09-19 at 12 40 42 PM

**Comment by laurendavissmith** [comment]
as another thought, if its too much trouble at this point to get the design worked in for this PR lets just get a follow-up story created before this gets merged and add it to the WCS sprint column

**Comment by bor0** [comment]
@laurendavissmith I can create an issue and work on it. The only reason I'd like to separate them is because this one specifically implements the ability to add a new package from the package details dialog.

**Comment by laurendavissmith** [comment]
@bor0 sounds good to me!

**Comment by bor0** [comment]
@roykho I believe I resolved https://github.com/Automattic/woocommerce-services/pull/1661#issuecomment-533188589 and https://github.com/Automattic/woocommerce-services/pull/1661#issuecomment-533200402 with the latest commits. Are there any other issues, or are they not resolved still?

**Comment by roykho** [comment]
@boro - ah ok, didn't see your latest changes. LGTM!

**Pull request merged**
