### PR TITLE
Partial removal of Calypso dependency

### PR DESCRIPTION
**Pull request by c-shultz**
## Description
This PR includes the on-going work in https://github.com/Automattic/woocommerce-services/issues/2333. 

This is the list of changes:
– Button from 'components/button'; (@brezocordero )✅
– Card from 'components/card'; ( @brezocordero ) ) ✅
– CompactCard from 'components/card/compact'; ( @brezocordero ) ) ✅
– Dialog from 'components/dialog'; ( @c-shultz ) ) ✅
– EllipsisMenu from 'components/ellipsis-menu'; ( @waclawjacek ) ✅
– FormFieldSet from 'components/forms/form-fieldset'; (@bborman22) ✅
– FormLabel from 'components/forms/form-label'; (@bborman22) ✅
– FormSelect from 'components/forms/form-select'; (@frosso ) ✅
– FormTextInput from 'components/forms/form-text-input'; (@bborman22) ✅
– FormTextInputWithAffixes from 'components/forms/form-text-input-with-affixes'; (@bborman22) ✅
– FormToggle from 'components/forms/form-toggle'; (@bborman22) ✅
– PaymentLogo from 'components/payment-logo'; ( @c-shultz ) ✅ 

### Related issue(s)
Closes https://github.com/Automattic/woocommerce-services/issues/2435

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Review by c-shultz — COMMENTED** [review]
Looking good to me:
- Created production build
- Installed on new Atomic site
- Purchased item
- Added package
- Checked WCS&T status screen
- Purchased and refunded real label on Chrome and Firefox

**Comment by c-shultz** [comment]
The production zip size went up from 1.5MB to 1.7MB and the unzipped size went down from 5.5MB to 5.4MB. I don't have any concerns about this change. 1.7MB still seems reasonable and the unzipped size is more important in my mind, so this still LGTM

**Review by brezocordero — APPROVED** [review]
Approving based on this comment: https://github.com/Automattic/woocommerce-services/pull/2343#pullrequestreview-695377515
And previous testing from other PRs on this branch.

**Review by harriswong — APPROVED** [review]
Tested the following:
- Able to purchase a label
- Able to refund a label
- Tracking package modal
- Tested "Live rates at checkout", "Carrier accounts" UI on `wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`. Making sure this still shows up. Also quickly tested DHL live rates, works. 
- Tested adding/updating/deleting package
- Clicked around `wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings` to make sure UI components still works

LGTM

**Pull request merged**
