### PR TITLE
Release 1.25.2

### PR DESCRIPTION
**Pull request by bborman22**
### Changes in this release
#2216 Add composer command to run PHPUnit
#2229 Fallback to open PDF in new tab if Safari does not print natively
#2230 Add ZIP code validation to UPS Sign up form
#2239 Create new endpoint for carrier types
#2241 Remove second parameter from getenv

This release branch is branched from latest `develop` 

### Test notes

- Test label purchase flow
- Test live rates
- Test Store on WP.com
- Test ZIP code validation
- Test printing labels on iOS with Safari
- Test composer PHPUnit command
- Test in PHP 5.3 looking for getenv warnings

### Changelog
* Tweak - Add ZIP code validation to UPS(beta) signup form.
* Fix       - Issue with printing labels in some iOS devices through Safari.
* Fix       - Prevents warning when using PHP 5.5 or lesser
* Add     - Add new API end point to retrieve carrier registration requirements.
* Add     - Add composer command to run PHPUnit.
* Tweak - Update readme with DHL information.

## Build File
Built from this branch using `php woorelease.phar simulate --product_version=1.25.2 https://github.com/Automattic/woocommerce-services/tree/release/1.25.2`

[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5502015/woocommerce-services.zip)

### CODE REVIEW

**Comment by harriswong** [comment]
Tested multiple items with multiple packages, shipped internationally.
- purchased 2 labels, 1 USPS, 1 DHL 
- verified shipping summary reads 'DHL' and 'USPS' separately.
- tested "mark this order as complete"
- confirmed 2 labels are printed (USPS + DHL)
- Confirmed email invoice receipt 
- Confirmed customer "Thanks for shopping with us" email contains 2 separate tracking for each

**Comment by harriswong** [comment]
@bborman22 I noticed the #2229 is mentioned but it is not in the commit logs. is it already released with 1.25.1?

**Comment by harriswong** [comment]
Confirmed commits for #2229 and #2230 are already in master. They are merged into the master after `1.24.1` when we merge `develop` back in.  👍

**Comment by bborman22** [comment]
@harriswong Thanks for taking a look! So I think those two got added to develop after the release/1.25.1 branch was created. Was this the right flow in that case and then having it listed in 1.25.2 like this?

**Comment by harriswong** [comment]
> Was this the right flow in that case and then having it listed in 1.25.2 like this?

I think so. I would have done the same thing since changes in `master` does not mean it has been released as a bundle. I was worried that my commits were missing 😅

**Review by c-shultz — APPROVED** [review]
Looks great to me, I tested:
- USPS live rates
- DHL label purchase
- USPS label purchase
- Purchased/printed label (from Firefox and Chrome)
- UPS registration form

**Comment by bborman22** [comment]
Since everything looks good, I'll be merging into master, do one more simulated release from the updated master branch and smoke test, then run the real release process. Once confirmed I'll be communicating the release!

**Pull request merged**
