### PR TITLE
1.24.3 patch

### PR DESCRIPTION
**Pull request by c-shultz**
The big driver for this patch is #2171 which is breaking WCS for users on some hosts with more restrictive security settings.

All changes slated for `1.24.3`:
#2166 
#2167 
#2175 
#2177 
#2171 
#2176 

Changelog for this release (once #2182 merges):
```
= 1.24.3 - 2020-XX-XX =
* Fix   - Asset paths incompatible with some hosts.
* Fix   - Select all posts checkbox not working.
* Fix   - Use of deprecated jQuery.load.
* Tweak - Updating carrier logo and tracking links
```

### CODE REVIEW

**Comment by c-shultz** [comment]
I made a quick PR to add some missing changelog entries: https://github.com/Automattic/woocommerce-services/pull/2182

We'll want to get that merged ahead of the release.

**Comment by c-shultz** [comment]
`1.24.3` test build created with `php woorelease.phar simulate --product_version=1.24.3 https://github.com/Automattic/woocommerce-services/tree/develop`

[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5228813/woocommerce-services.zip)

**Comment by c-shultz** [comment]
I'll give it some more testing tomorrow (specifically planning on: UPS, live rates, and clicking around WC admin screens), but it's looking to me so far:
- Activated from the "Create Shipping Label" prompt from wc-admin
- Added a custom package
- Ordered a test label

**Review by Ferdev — APPROVED** [review]
Looks good! Everything worked nicely in two JN sites + localhost.

**Review by frosso — APPROVED** [review]
Tested on Jurassic Ninja
- ✅  Live Rates
- ✅  Status pages
- ✅  Label creation
- ✅  Label purchase
- ✅  Label refund

I did find a little 🐛  while testing, but it seems to be present also in the previous release, so not related to these changes.
I created a separate ticket for it: https://github.com/Automattic/woocommerce-services/issues/2185

**Comment by bborman22** [comment]
Tested on JN with staging server:

- USPS label purchase and refund
- Connect UPS account and purchase/refund a UPS label
- Live rates from USPS
- Tax calculations
- Updated some settings on each WooCommerce setting page

It all looked good to me!

**Comment by c-shultz** [comment]
Thanks for testing, all! 💯

**Pull request merged**
