### PR TITLE
Run JS unit tests in travis

### LINKED ISSUE #1921: Add Javascript tests to Travis
We have lots of Javascript tests we could add to our Travis matrix.

You can try them by running:

`npm run test-client`

### PR DESCRIPTION
**Pull request by superdav42**
Let's see if it works

Closes #1921

### CODE REVIEW

**Comment by c-shultz** [comment]
My tests are all failing now 😱 . Do they work for you locally @superdav42? I wonder if there's a version difference causing. I'm running v6.9 of npm. Travis appears to be using 10, but I'm not sure if the npm version makes sense for just making the tests fail.

**Comment by superdav42** [comment]
> My tests are all failing now  . Do they work for you locally @superdav42? I wonder if there's a version difference causing. I'm running v6.9 of npm. Travis appears to be using 10, but I'm not sure if the npm version makes sense for just making the tests fail.

Tests work for me locally. I doubt it's an npm problem. I'm sure it's related to timezones because travis will have a different TZ than us. I tried to fix it in https://github.com/Automattic/woocommerce-services/pull/1936/commits/08005028e248f2137bfa134445f573bc83226b63 but it didn't work. Not sure what else to try.

**Comment by superdav42** [comment]
Had to use moment.tz to set default timezone. All tests passing now.

**Comment by c-shultz** [comment]
Closes #1921

**Pull request merged**
