### PR TITLE
Skip during WooCommerce Store API requests

### PR DESCRIPTION
**Pull request by seb86**
## Description
Allows the WooCommerce Store API to send for a request.

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Review by c-shultz — CHANGES_REQUESTED** [review]
Hey @seb86,

Thanks for the PRs! I have just added this to the team review queue now so we'll get to the review when we can. I expect it will take a couple weeks at this point given our priorities.

A few initial requests (this applies to all your PRs so I'll cross link this comment):
- It looks some conflicts with `develop` have creeped in. Can you merge or rebase to clear those up?
- Please create an entry in the changelog.txt (not sure if that should be just be a single entry or multiple entries between #2289 #2288 and #2291)
- Can you provide some more detailed testing/usage instructions to help the reviewer out on these?
- If possible, it would be great to get some unit test coverage on these PRs. [We some unit test info here](https://github.com/Automattic/woocommerce-services/blob/develop/CONTRIBUTING.md)

**Comment by nerrad** [comment]
There's some overlap here with recent work done in #2372 and #2325.

**Comment by c-shultz** [comment]
This has been quiet for a while. I'm going to close these, but please contact us again if you wish to revisit this! Thanks!

**Comment by c-shultz** [comment]
This has been quiet for a while. I'm going to close these, but please contact us again if you wish to revisit this! Thanks!

**Pull request closed without merging**
