### PR TITLE
release 1.25.6

### PR DESCRIPTION
**Pull request by frosso**
### Changes in this release
- https://github.com/Automattic/woocommerce-services/pull/2293 : Refreshes shipping methods after registering or removing carrier accounts
- https://github.com/Automattic/woocommerce-services/pull/2301 : Changed rates response caching method from cache to transient
- https://github.com/Automattic/woocommerce-services/pull/2308 : chore: update WC version

This release branch is branched from latest `develop` .

### Test notes
- Test against WC 5.0 beta (use the [WC beta tester plugin](https://wordpress.org/plugins/woocommerce-beta-tester/) for an easy switch)
- Test live rates
- Test account connection

### Changelog
* Fix 	- Refreshes shipping methods after registering or removing carrier accounts.
* Tweak	- Changed rates response caching method from cache to transient.

## Build File
Built from this branch using `php woorelease.phar simulate --product_version=1.25.6 https://github.com/Automattic/woocommerce-services/tree/release/1.25.6`

[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5857026/woocommerce-services.zip)

### CODE REVIEW

**Comment by c-shultz** [comment]
Let's get the `WC tested up to` value bumped up to `5.0` in this release. WC Core warns on "major" version updates if the plugin does not indicate that it's tested with that major version. Sites may see a warning as they upgrade to 5.0. This [warning functionality is being disabled](https://github.com/woocommerce/woocommerce/pull/28840) since WC core is moving away from SemVer, but sites getting update from 4.91 or lower to 5.0 would still see the warning unless we update the `tested up to` value in WCS.

**Comment by frosso** [comment]
@c-shultz thanks for the notice! [I created a PR](https://github.com/Automattic/woocommerce-services/pull/2308) to update the value in the plugin.
I also updated the testing instructions here (and on the related P2) to test against 5.0-beta1 (the latest available at the time of writing).

I will integrate the PR changes in this branch and create a new `.zip` archive as soon as the PR is merged.

**Comment by c-shultz** [comment]
Thanks!

**Comment by harriswong** [comment]
Setup: JN store with latest WP and WC 5.00 beta2
✅  Tested domestic US-US shipping with USPS. Able to print labels
✅  Confirmed email received from label purchases
✅  Tested DHL Express live rate on US-Canada international shipping
✅  Tested multiple label purchases with different packages
✅  Tested DHL Express registration connect and disconnect button

**Pull request merged**
