### PR TITLE
Update Calypso dependency

### PR DESCRIPTION
**Pull request by DanReyLop**
I've just made a smoke test of the shipping settings page, https://github.com/Automattic/wp-calypso/pull/25101 is solved.

The changes brought form Calypso are:
- https://github.com/Automattic/wp-calypso/pull/23658
- https://github.com/Automattic/wp-calypso/pull/24715
- https://github.com/Automattic/wp-calypso/pull/25101 (confirmed, it works)

### CODE REVIEW

**Comment by dechov** [comment]
I believe https://github.com/Automattic/wp-calypso/pull/23658 is the only other merged PR. Testing it now

**Comment by DanReyLop** [comment]
@dechov Automattic/wp-calypso#24715 too, but that doesn't apply to WP-Admin. Ping me when you're done and I'll cut a release :)

**Comment by dechov** [comment]
You're right – it doesn't apply to WP-Admin but still I put it too far out of mind 😄

Everything from Automattic/wp-calypso#23658 is working well.

Why is `"dev": true` being added in the shrinkwrap?

**Comment by DanReyLop** [comment]
> Why is "dev": true being added in the shrinkwrap?

I guess some dependencies changed in `wp-calypso`. Everything that change is under the `wp-calypso` dependency so I'm not worried that we messed up updating.

**Pull request merged**
