### PR TITLE
Replace colors package with chalk in release.js script

### PR DESCRIPTION
**Pull request by bartech**
## Description

Replace colors npm package with chalk in `tasks/release.js` script for building plugin zip.

### Related issue(s)
#2536 

### Steps to reproduce & screenshots/GIFs
run `npm i && npm run release`
Release script should work as before change and show colored messages. 

### Checklist

- [x] unit tests

- [ ] `changelog.txt` entry added
No changelog entry as this is development dependency change.

### CODE REVIEW

**Comment by bartech** [comment]
Not sure if I should commit changes in `npm-shrinkwrap.json` as this is what was changed after I added chalk and removed colors as dependency,

**Review by iyut — CHANGES_REQUESTED** [review]
LGTM, only minus with changelog. Can you add the changelog please?

**Comment by iyut** [comment]
> Not sure if I should commit changes in `npm-shrinkwrap.json` as this is what was changed after I added chalk and removed colors as dependency,

Since we're replacing one of their library, I believe we need to commit the npm-shrinkwrap as well. But it will be better if you could confirm with them from A8C slack group first.

**Comment by bartech** [comment]
@iyut 
> Can you add the changelog please?

Though changelog is only for customer facing features or bugs. This change is only developer side don't think we want to inform plugin users about internals.

**Comment by iyut** [comment]
> This change is only developer side don't think we want to inform plugin users about internals.

Do you mind to check in changelog file if there is any log for internal changes? I thought there are a couple of internal changes being listed in there.

**Comment by bartech** [comment]
I'm closing this PR as this fix is also included in PR #2566 that address E2E and JS Test fixes.
I branched from fix/issue-2536 branch and think this will be easiest to continue.
Please continue review on new PR.

**Pull request closed without merging**
