### PR TITLE
Include labels for tracking and delivery days

### PR DESCRIPTION
**Pull request by bor0**
Fixes https://github.com/Automattic/woocommerce-connect-server/issues/1303.

### CODE REVIEW

**Comment by bor0** [comment]
Make sure to mock `delivery_days` when testing this. `woocommerce-connect-server` returns null (which comes from EasyPost API) but I believe it's due to test mode? 🤷‍♂

**Comment by laurendavissmith** [comment]
> returns null (which comes from EasyPost API) but I believe it's due to test mode

how would we confirm this?

**Comment by bor0** [comment]
I don't know if we have an actual prod setup somewhere? Or even just prod EasyPost API keys. We just want to see what data it returns with that setup.

**Comment by bor0** [comment]
Sent an e-mail to Brian at EasyPost. Rel: https://a8c.slack.com/archives/CKNC7KACA/p1570805292009400

**Comment by bor0** [comment]
Answer to our e-mail:

> Hello Boro,
> 
> There's a few relevant pieces of information you should be aware of, regarding the delivery_days​ field.
> 
> First, that field is not always expected to be populated; whether or not it is is dependent on the carrier and the service level in particular. This leads to my second note: The service level of the rate you've provided, USPS Express, is a sort of special case. We'd need to set a flag to populate that value for Express shipments, because doing so slows down the API response by as much as 500ms. I will forward a request to have that flag set if you explicitly wish me to do so, but I would advise against it unless it is critical to your use case. However, if you only need some rate object with that field populated, you should be able to use any of the other rates on that particular shipment:
> 
> ```
> [
>   {
>     "object": "Rate",
>     "created_at": "2019-10-11T17:49:48Z",
>     "updated_at": "2019-10-11T17:49:48Z",
>     "mode": "test",
>     "service": "Priority",
>     "carrier": "USPS",
>     "rate": "7.04",
>     "currency": "USD",
>     "retail_rate": "8.30",
>     "retail_currency": "USD",
>     "list_rate": "7.61",
>     "list_currency": "USD",
>     "delivery_days": 1,
>     "delivery_date": null,
>     "delivery_date_guaranteed": false,
>     "est_delivery_days": 1,
>     "shipment_id": "shp_490c7108462d4335b5d630620f8441fd",
>     "carrier_account_id": "ca_7ae99212c7714a439f2b27d3f3b3e33b",
>     "id": "rate_97580423d10742afaf4a961f4eaed094"
>   },
>   {
>     "object": "Rate",
>     "created_at": "2019-10-11T17:49:48Z",
>     "updated_at": "2019-10-11T17:49:48Z",
>     "mode": "test",
>     "service": "Express",
>     "carrier": "USPS",
>     "rate": "21.24",
>     "currency": "USD",
>     "retail_rate": "25.80",
>     "retail_currency": "USD",
>     "list_rate": "22.83",
>     "list_currency": "USD",
>     "delivery_days": null,
>     "delivery_date": null,
>     "delivery_date_guaranteed": false,
>     "est_delivery_days": null,
>     "shipment_id": "shp_490c7108462d4335b5d630620f8441fd",
>     "carrier_account_id": "ca_7ae99212c7714a439f2b27d3f3b3e33b",
>     "id": "rate_7849ee76b63e4eba9c4d0b25c2eb3fd8"
>   },
>   {
>     "object": "Rate",
>     "created_at": "2019-10-11T17:49:48Z",
>     "updated_at": "2019-10-11T17:49:48Z",
>     "mode": "test",
>     "service": "MediaMail",
>     "carrier": "USPS",
>     "rate": "3.79",
>     "currency": "USD",
>     "retail_rate": "3.79",
>     "retail_currency": "USD",
>     "list_rate": "3.79",
>     "list_currency": "USD",
>     "delivery_days": 2,
>     "delivery_date": null,
>     "delivery_date_guaranteed": false,
>     "est_delivery_days": 2,
>     "shipment_id": "shp_490c7108462d4335b5d630620f8441fd",
>     "carrier_account_id": "ca_7ae99212c7714a439f2b27d3f3b3e33b",
>     "id": "rate_0bedd9cbab654ba9b322d73ad2f83fd0"
>   },
>   {
>     "object": "Rate",
>     "created_at": "2019-10-11T17:49:48Z",
>     "updated_at": "2019-10-11T17:49:48Z",
>     "mode": "test",
>     "service": "ParcelSelect",
>     "carrier": "USPS",
>     "rate": "7.51",
>     "currency": "USD",
>     "retail_rate": "7.51",
>     "retail_currency": "USD",
>     "list_rate": "7.51",
>     "list_currency": "USD",
>     "delivery_days": 2,
>     "delivery_date": null,
>     "delivery_date_guaranteed": false,
>     "est_delivery_days": 2,
>     "shipment_id": "shp_490c7108462d4335b5d630620f8441fd",
>     "carrier_account_id": "ca_7ae99212c7714a439f2b27d3f3b3e33b",
>     "id": "rate_6028028ee128401fa37f655c25238141"
>   }
> ]
> ```
> 
> You'll note that the `delivery_days` field is populated for the other three USPS service level rates.
> 
> Let me know if this addresses the need of your use case, or if you'd like me to request that flag be set for the account, or if you have any other questions.
> 
> Kind regards,
> Tyler C | EasyPost Support

**Comment by bor0** [comment]
I will merge this because regardless of the decision, the code will be the same. We can discuss this on the team meeting.

**Pull request merged**
