### PR TITLE
release: 1.25.0

### PR DESCRIPTION
**Pull request by c-shultz**
### Changes in this release
#2186 Fix UPS connect redirect prompt
#2188 PHP 8 compatibility fix
#2189 Allow UPS label purchases with no credit card
#2194 String validation for service insurance
#2198: PR template (code not affected)
#2201: DHL notification pointer
#2207: Use square DHL logo in rate list
#2204 / #2213 Allow merchants to print customs form
#2199 Fix PHP notice
#2179 Plugin rename

This release branch is branched from latest `develop` 

### Test notes

- Test DHL ( see: https://wcship.wordpress.com/2020/09/24/dhl-for-wcship-call-for-testing/ )
- Test live rates
- Test Store on WP.com
- Test DHL notification
- Test customs forms for DHL and UPS

### Changelog
* Fix   - UPS connect redirect prompt
* Fix   - Allow UPS label purchase without payment method
* Fix   - PHP implode arguments order
* Fix   - Validate insurance value as both string and number
* Tweak - Adjusted messaging on label pointers
* Tweak - Update carrier logo
* Tweak - Plugin rename
* Add   - Link to print the customs form for all shipments that need it

## Build File
Built from this branch using ` php woorelease.phar simulate --product_version=1.25.0 https://github.com/Automattic/woocommerce-services/tree/release/1.25`

[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5351614/woocommerce-services.zip)

### CODE REVIEW

**Comment by Ferdev** [comment]
I've found a bug while testing Store on WP.com: if you try to purchase a DHL label through Store on WP.com, the purchase fails. USPS labels do work, but I couldn't test UPS labels (cannot register the UPS account in staging, don't know why).

I'm gonna try to reproduce it locally. I'll be back with more news.

**Comment by c-shultz** [comment]
>cannot register the UPS account in staging, don't know why
This is a known issue because the test EasyPost api does not allow child account creation.

**Comment by Ferdev** [comment]
> This is a known issue because the test EasyPost api does not allow child account creation.

Oh, Ok, no problem. I don't know why, I thought this had been fixed.

**Comment by frosso** [comment]
@Ferdev will be fixed on Monday, with the next server release 👍
Related PR: https://github.com/Automattic/woocommerce-connect-server/pull/1562

**Review by frosso — APPROVED** [review]
Looks good 👍 

✅  DHL Live Rates
✅  DHL Labels
✅  DHL Refund
✅  Customs form
✅  USPS Live Rates
✅  USPS Labels
✅  USPS Refund
✅  DHL/USPS notification

Also having some issues with the UPS connection, but it seems to be on the server side

**Comment by Ferdev** [comment]
Found the problem with Store on WP.com. I've created an issue to track it: 109-gh-woocommerce-shipping-issues

**Comment by harriswong** [comment]
For UPS testing, we will need to setup the prod/test key in the sandbox DB

✅ Tested USPS label
✅ Tested USPS refund
✅ Tested USPS refund with "parcel already shipped" error
✅ Tested DHL label
✅ Tested DHL reprint label
✅ Tested DHL print custom form
✅ Tested UPS label
✅ Tested UPS refund
✅ Verified insurance shows for DHL

❌ UPS custom form missing for international shipping, is this expected?
image

**Comment by bborman22** [comment]
✅  DHL Live Rates / Labels / Refund
✅  USPS Live Rates / Labels / Refund
✅  DHL / USPS notification
✅  Customs form (Chrome did block the new tab, but was able to unblock and/or access from the label dropdown)
✅  Calculated Taxes

Looks good to me!

**Comment by c-shultz** [comment]
>UPS custom form missing for international shipping, is this expected?

Yeah, it will be left off unless we create a shipment to a country that requires a printout of the form

**Comment by c-shultz** [comment]
Looks like we're good to go! I'm going to go ahead, and:
- Merge to `master`
- Simulate the release with woorelease (and test the build)
- Deploy it

**Pull request merged**
