### PR TITLE
Release 1.25.3

### PR DESCRIPTION
**Pull request by bborman22**
### Changes in this release
#2245 Add WC Helper connection information to requests
#2238 Allows package dimension input to begin with zero
#2243 Add dynamic carrier account registration form
#2244 Adds more specific validation to UPS connect form
#2261 Add link to schedule pickup for DHL Express
#2259 Fix signature required checkbox not updating prices
#2233 Add message to explain exclusive tax is needed for automated tax service
#2266 Disable USPS refunds for labels without tracking id.

This release branch is branched from latest `develop` 

### Test notes

- Test label purchase flow
- Test live rates
- Test Store on WP.com
- Test all functionality with and without a connection to WooCommerce.com
- Test package dimensions starting with 0
- Test UPS connect form input validation
- Test DHL Express schedule pick up link
- Test signature required pricing updates
- Test automated taxes messaging for exclusive tax pricing
- Test USPS refunds are not available for labels with no tracking ID

### Changelog
* Add   - Initial code for WooCommerce.com subscriptions API.
* Add   - Dynamic carrier registration form.
* Fix     - When adding "signature required" to some packages, prices were not updating.
* Add   - DHL Schedule Pickup link within order notes.
* Fix     - UI fix for input validation for package dimensions and weights.
* Fix     - Correct validation for UPS fields in Carrier Account connect form.
* Tweak - Add message to explain automated tax requires tax-exclusive product pricing.
* Fix   - Disable USPS refunds for untracked labels only.

## Build File
Built from this branch using `php woorelease.phar simulate --product_version=1.25.3 https://github.com/Automattic/woocommerce-services/tree/release/1.25.3`

**Updated November 23rd**
[woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5583341/woocommerce-services.zip)

### CODE REVIEW

**Comment by c-shultz** [comment]
@bborman22 let's also get this PR into this patch: https://github.com/Automattic/woocommerce-services/pull/2266

More context on that here: https://a8c.slack.com/archives/CTYKKGC1Y/p1605824084097900

**Comment by bborman22** [comment]
I have updated the PR and the plugin build to include #2266.

**Review by Ferdev — APPROVED** [review]
Looks good to me! Only found one problem:
In Firefox, after you purchase a label in Store on .com, the purchase label modal window cannot be closed afterwards. If you click out of the modal, it doesn't close the modal and does nothing instead.
But I think that's just an old issue, I don't think it was introduced in this build.
I'll create an issue to tackle the Store on .com problem separately.

**Comment by harriswong** [comment]
- Tested USPS label purchase
- Tested USPS label refund
- Tested DHL purchase
- Tested DHL refund (not automatic refund)
- Tested DHL live rate, checked to make sure it matches label purchase rates. 
- Tested UPS registration form
- Tested UPS purchase/refund + signature required, additional price included
- Tested "Mark this order as complete and notify the customer", email received
- Confirmed DHL Schedule pickup link open DHL page
- Confirmed automated tax message updated
- Confirm UPS disconnect works

LGTM 👍

**Pull request merged**
