### PR TITLE
Update shipping label endpoint to support return labels

### PR DESCRIPTION
**Pull request by dechov**
Adapt shipping label endpoint to the case of a return label being purchased:
- pass back label ID being returned
- allow for missing <s>`service_name` and</s> `box_id` and `products` in shipping label endpoint

**Support for return labels on server required for release.**

### CODE REVIEW

**Comment by dechov** [comment]
If this change is necessary, I think we'll need a feature flag for https://github.com/Automattic/wp-calypso/pull/23183 — we can work around the `service_name` (in request) and `box_id` (in response) in the calypso and server PRs respectively, but I don't know how we can provide a good experience without passing `returning_label_id` back through in the response.

**Comment by dechov** [comment]
No longer supporting missing data — instead, this PR serves only to provide more data to the client: `box_id`, `product_ids`, and `returning_label_id`.

**Comment by v18** [comment]
Note: This PR is related to these two:

https://github.com/Automattic/woocommerce-connect-server/pull/1055 (currently being reviewed by me)
https://github.com/Automattic/wp-calypso/pull/23183 (currently being rebased + refactored into smaller PRs)

**Comment by v18** [comment]
@dechov just double-checking - is this PR still ready for review? Or does it need some changes to accommodate the new api endpoint from https://github.com/Automattic/woocommerce-connect-server/pull/1055 ?

**Comment by dechov** [comment]
@v18 Thanks – we need to adapt to those changes and may want a new endpoint here too.

**Comment by millerf** [comment]
@gwwar I think this one can be deleted...

**Pull request closed without merging**
