### PR TITLE
deps: add yarnhook

### PR DESCRIPTION
**Pull request by frosso**
## Description

It can happen that we add/remove dependencies between merges.
But it can also happen that not everyone remembers to run `npm install` after new updates.

`yarnhook` detects changes on `npm-shrinkwrap.json` to determine whether or not we need to run `npm install` after checking out a new branch or updating our local branch.

It doesn't mean that it can fail - in my experience it might not run when rebasing or resolving merge conflicts. But it's a helpful tool, I think.

https://github.com/frontsideair/yarnhook

### Steps to reproduce & screenshots/GIFs

* Check out this branch
* Run `npm install` to get `yarnhook`
* Run `git checkout -b test-deps && npm install --save-dev addition && git add . && git commit -nam "test add"` to add a random dependency to a new temp branch
* Run `git checkout frosso/add-yarnhook`
* You should see the dependencies update running (because of the change of branch)
* Run `git branch -D test-deps` to delete the temp branch

### Checklist

- [ ] unit tests

- [ ] `changelog.txt` entry added

### CODE REVIEW

**Comment by harriswong** [comment]
👀

**Review by harriswong — COMMENTED** [review]
I got an error:
```
added 2241 packages in 47.14s
husky - Git hooks failed to install
EEXIST: file already exists, mkdir '.husky/_'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! woocommerce-services@1.25.15 prepare: `cd wp-calypso && npm ci && cd .. && husky install`
npm ERR! Exit status 1
npm ERR!
```

My commands were:
```
git checkout frosso/add-yarnhook
npm i
git checkout -b test-deps && npm install --save-dev addition && git add . && git commit -nam "test add" // this runs well
git checkout trunk //good
git checkout frosso/add-yarnhook //errors
git checkout test-deps //errors
```

I have a few thoughts on this tool. I think automating `npm i` has these pros:
- This helps prevent bugs related to older packages. Especially if the branch updated `packages.json`
- Making sure your branch is always using the packages according to shrinkwrap/lock

In my experieince working with woocommerce-payments, i have these issues:
- Makes rebasing slower especially if main branch requires dependency updates
- Makes branch switching slower
- Running `npm i` on demand didn't seem too much of a hassle. But the issue was to remember running it. 

I personally find that it slows down development time but I would like to hear what others think as well.

**Comment by harriswong** [comment]
I ran `nvm i` to make sure i am on `10.16` and repeated these commands
```
git checkout frosso/add-yarnhook
git checkout test-deps 
```

Seems like the error disappeared now.

**Comment by frosso** [comment]
@harriswong thanks!
I was just going to reply 😄 

I rebased this branch with the changes on `trunk` and ran your commands on my machine, they seem to be working ok now 🤷

**Comment by harriswong** [comment]
Woops, this slipped my mind.

**Comment by harriswong** [comment]
👀

**Review by harriswong — APPROVED** [review]
Tested the steps. Confirmed dependency updates after switching branch back. 👍

**Pull request merged**
