### PR TITLE
Declare HPOS incompatibility

### PR DESCRIPTION
**Pull request by waclawjacek**
Since #2577 is still under review, declaring HPOS incompatibility for the time being.

### CODE REVIEW

**Comment by harriswong** [comment]
I think I reviewed the WCS&T one and it looks good to me. We can probably merge that instead of declaring it as incompatible?

**Comment by waclawjacek** [comment]
Sure! If you have completed your review, let's do that instead! Feel free to close this one if that is correct.

**Comment by harriswong** [comment]
I think it's still pending another approval. I will just approve this one.

**Review by harriswong — APPROVED** [review]
`before_woocommerce_init` LGTM

**Comment by bartech** [comment]
#2577 is ready to be merged. Last blocker was failing e2e that was introduced by changes in WooCommerce e2e test.  As this is solved and all test are passing HOPS feature is ready.

**Comment by bartech** [comment]
I'm closing this one so we don't merge two contradicting changes. If you decide to declare incompatibility for time being please re-open and merge this PR.

**Pull request closed without merging**
