### PR TITLE
1.24.2 release merge

### PR DESCRIPTION
**Pull request by c-shultz**
Creating patch to get #2156 out ahead of WooCommerce 4.5 release

Changes in this patch:
#2135 
#2134 
#2151 
#2158 
#2156 
#2159 
#2140 

For testing, I don't see any unusual areas of functionality that needed to be tested, I would focus on:
- Purchase and refund a test label for USPS
- Try to connect a UPS account with wrong information and verify that error is shown
- Connect UPS account with good account information
- Print test UPS label

I'll attach a build zip in the comments.

From Changelog:

> * Fix   - Optional preloading for wc-admin install compatibility
> * Fix   - Remove duplicate rate errors
> * Fix   - Compatibility with WooCommerce order page install prompt
> * Add   - Introduce 'wc_connect_meta_box_payload' filter for modifying order data
> * Tweak - Update UPS failed connection error message

### CODE REVIEW

**Comment by c-shultz** [comment]
Production build (from `npm run build`): [woocommerce-services.zip](https://github.com/Automattic/woocommerce-services/files/5159178/woocommerce-services.zip)

**Review by Ferdev — COMMENTED** [review]
I've been testing it thoroughly on a Jurassic Ninja site, and everything worked with USPS labels. I had no issues at all with that.

But I couldn't link my UPS account using the data in the Secret Store. I got the error message about invalid form data.

Also,something weird happened while testing Calypso integration. I purchased a USPS label through Calypso, and when the label as ready to print and the "Print" button was displayed in the modal window, I wanted to close that modal by clicking the modal background. What happened instead, is the "Print" button morphed to "Purchase" with the loading animation. I could print and refund the label after reloading the whole page, though.

Another error I had while testing Calypso was intermittent connection errors to WC Connect Server while trying to get a rate for my labels. I think this was caused by my setup, but I'd appreciate if someone could confirm this issue is not happening to them.

**Comment by bborman22** [comment]
I tested on a clean install on Jurassic Ninja and had no issues. Ran some of the following tests:

1. Install and setup/connect.
2. Purchase USPS and UPS label.
3. Refund USPS and UPS label.
4. Get USPS Live Rates.
5. Printed and Refunded a USPS label from Calypso.
6. Calculate taxes within known rate.

Everything looked good from my testing!

**Comment by c-shultz** [comment]
> Also,something weird happened while testing Calypso integration. I purchased a USPS label through Calypso, and when the label as ready to print and the "Print" button was displayed in the modal window, I wanted to close that modal by clicking the modal background. What happened instead, is the "Print" button morphed to "Purchase" with the loading animation. I could print and refund the label after reloading the whole page, though.

The Calypso UI worked OK on my end. The local dev setups have usually been flaky in my experience, and I don't see any changes that could affect it, so I think we're good!

The UPS account registration issues look unrelated. It will be great when we can work with UPS to streamline that process.

**Pull request merged**
