### PR TITLE
Fix PHP 5 compatibility issues

### LINKED ISSUE #2401: Syntax error
We get a syntax error on our wordpress site and it lists a woocommerce-services file as the problem. This happened after an update
``
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /users/trc-foundation.org/htdocs/fillingthegap/wp-content/plugins/woocommerce-services/classes/class-wc-connect-shipping-label.php on line 323
``

### PR DESCRIPTION
**Pull request by bborman22**
## Description
We had received a report of a syntax error for some PHP 7 syntax (return type and string parameter type in functions). To meet the requirement of PHP 5.6 compatibility, I removed this additional syntax. To confirm there were not additional issues, I ran the [PHPCompatibility tool](https://github.com/PHPCompatibility/PHPCompatibility) to look for further issues and address them all at once.

### Related issue(s)
Fixes #2401 

### Steps to reproduce & screenshots/GIFs
1. Set up a site using PHP 5.6 and older version of WC (I used 4.1 to test: https://wordpress.org/plugins/woocommerce/advanced/)
2. Find a shippable order ID.
3. Make a GET request to your store API endpoint: connect/label/<order_id>/creation_eligibility
4. Confirm syntax error.
5. Update to this branch and request again.
6. Confirm no syntax error.

PHP56-errors

PHP56-noerrors

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

### CODE REVIEW

**Comment by harriswong** [comment]
Do we need to support PHP < 7? https://docs.woocommerce.com/document/server-requirements/.

**Comment by bborman22** [comment]
I honestly wasn't too sure, I just put this up since it was a really quick fix and we don't use the PHP 7 syntax elsewhere. If we aren't supporting PHP < 7, we should bump up our WC requirement to at least 3.9 I believe based on this: https://github.com/woocommerce/woocommerce/pull/26090. We could make that requirement bump instead of or in addition to this PR as well?

**Comment by harriswong** [comment]
Yea, this overlaps with [this](https://github.com/Automattic/woocommerce-services/issues/2365#issuecomment-794310786) as well.

I think it is a good idea to roll this out while we decide our versioning.

**Comment by bborman22** [comment]
Yeah I was thinking it's a quick win in the meantime, but I like the direction of that other discussion and think that bump in supported WC version (and thus PHP version) would be a good thing.

**Comment by Ferdev** [comment]
Hey @bborman22 ! I've been trying to test this PR, but I cannot complete the setup. I always get stuck trying to connect Jetpack. 

If I try to connect using WC 4.1 and latest WS&T version, it gives an unspecified error after pressing the "Install Jetpack and connect" button.

If I use latest WC and WS&T version with PHP 7, connect Jetpack, and then downgrade PHP to 5.6 and WC to 4.1, I get runtime errors coming from the Jetpack plugin...

maybe you can help me setup the PHP 5.6 site?

**Comment by bborman22** [comment]
Hmm, that second option is what I did. I had a working site up with latest and did the downgrades. I sent some testing information to you on Slack, but let me know if you run into any other issues with the setup!

**Review by Ferdev — APPROVED** [review]
I followed your recommendation and tried on a JN site, and I managed to make it work. Thanks for the help!
I've been testing the whole site thoroughly, and everything worked perfectly.

**Pull request merged**
