### PR TITLE
Use square image for DHL logo.

### PR DESCRIPTION
**Pull request by c-shultz**
## Description
Replaces DHL logo with a square image provided by @elizaan36 to improve the display of the logo in the rates list.

### Steps to reproduce & screenshots/GIFs
Enable DHL rates for site and get rates (using a non-US destination address)

Before:
image

After:
image

### Checklist

- ~[ ] unit tests~ **(not applicable)**

- [x] `changelog.txt` entry added

### CODE REVIEW

**Comment by harriswong** [comment]
I like how the pipeline failed for the image. :D

**Review by harriswong — APPROVED** [review]
Confirmed image is a square. LGTM 👍 

🚢  if pipeline passes

**Comment by c-shultz** [comment]
>I like how the pipeline failed for the image. 

Very strange. It looks like it stalled out while cloning. I'm going to re-run it 🤞

**Comment by c-shultz** [comment]
I guess that worked 🤷

**Pull request merged**
