### PR TITLE
Fix/issue 2565 - Update WP Calypso to newer commit to fix the 'npm run prepare' error

### LINKED ISSUE #2565: Plugin builds are very slow and contain `make` errors related to `fsevents`
Attempts to build the plugin result in a really lengthy build. We need to look why this is the case.

## How to reproduce

1. Check out `trunk`
2. In the plugin directory, run: `nvm use && npm run prepare`
3. The build will take a really long time, seemingly stalling during `extractTree` or other steps (this is expected although not desired :)).
4. The build process will finish successfully but with errors.
5. The same issue will happen on subsequent attempts to run `npm run prepare`

An error like this should appear:

```
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit



gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node" "/Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents
gyp   SOLINK_MODULE(target) Release/fse.node
ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node /Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node" "/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node /Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
  COPY /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stampfsevents@1.2.7~install: fsevents@1.2.7
gyp info ok 
```

## Research done so far

I have done some research around this but I was unable to pinpoint the exact cause for this issue. I am including the findings so far:

1. Installing `python2` resolved some errors.
1. Then, discovered that the issue is with the `fsevents` library that two dependencies in wp-calypso are using (`chokidar` and another dependency prefixed with `jest-` - can't recall).
   * Calypso itself is pulled into WCS&T as a Git submodule.
1. The issue is that the binary for the specific version of `fsevents` is no longer available (IIRC, maintainer lost access to the server where binaries were hosted) and the library falls back to building the binary on your local machine instead. I think this is what is taking the most time.
   * Possible solution ideas (untested): upgrade Calypso version/try getting the binary to build.

### PR DESCRIPTION
**Pull request by iyut**
## Description
Update wp-calypso commit to [this commit](https://github.com/Automattic/wp-calypso/commit/79b83cb343521370813bc052b2789d3245cd9698) to fix the `npm run prepare` error.

### Related issue(s)

Fixes #2565 

### Steps to reproduce & screenshots/GIFs

- Run `git checkout fix/issue-2565`.
- Run `git submodule update`.
- Run `npm run prepare` and `npm run dist`.
- Make sure there is no error when in the terminal.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

### CODE REVIEW

**Comment by bartech** [comment]
@iyut you can add me for review here. I tested on my local and updated calypso version works, can vouch this is ok 👍

**Comment by iyut** [comment]
> I tested on my local and updated calypso version works, can vouch this is ok 👍

Thanks a lot for testing this @bartech, and I have added you as a reviewer.

**Review by bartech — APPROVED** [review]
I tested on my local and updated calypso version works, was able to successfully run `npm run prepare`

**Comment by bartech** [comment]
@iyut Merged #2566 please merge trunk into this branch so we can perform E2E on this change. Please update changelog to resolve conflicts.

**Pull request merged**
